name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  # Job to build the application
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

  # Job to test the code
  test:
    runs-on: ubuntu-latest
    needs: build  # This job will only run if the 'build' job is successful
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  # Job to deploy the application
  deploy:
    runs-on: ubuntu-latest
    needs: test  # This job will only run if the 'test' job is successful
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.PAT_TOKEN }}
          repo_token: ${{ secrets.PAT_TOKEN }}
          action: 'upload'
          app_location: '/'  # Adjust if necessary
          api_location: 'api'  # Adjust if necessary
          output_location: 'build'
