name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm test  # Assumes your test script is defined in package.json

  build_and_deploy_job:
    runs-on: ubuntu-latest
    needs: test  # Ensure the build only runs if tests pass
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build  # Assumes your build script is defined in package.json

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.PAT_TOKEN }}
          repo_token: ${{ secrets.PAT_TOKEN }}
          action: 'upload'
          app_location: '/'  # Adjust if necessary
          api_location: 'api'  # Adjust if necessary
          output_location: 'build'
