name: Full CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Change directory
        run: cd app

      - name: Install dependencies
        run: npm install
        working-directory: app

      - name: Run tests
        run: npm test
        working-directory: app

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Change directory
        run: cd app

      - name: Install dependencies
        run: npm install
        working-directory: app

      - name: Build the application
        run: npm run build
        working-directory: app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Change directory
        run: cd app

      - name: Build the application (for deployment)
        run: npm run build
        working-directory: app

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.PAT_TOKEN }}
          repo_token: ${{ secrets.PAT_TOKEN }}
          action: 'upload'
          app_location: '/'  # Adjust if necessary
          api_location: 'api'  # Adjust if necessary
          output_location: 'build'
