name: Azure Static Web Apps CI/CD
 
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
 
permissions:
  contents: write
  workflows: write
 
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
 
      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.PAT_TOKEN }}
          repo_token: ${{ secrets.PAT_TOKEN }}
          action: 'upload'
          app_location: '/'
          api_location: 'api'
          output_location: 'build'
